# Generated by Django 4.2.5 on 2023-12-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentPortal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentName',
        ),
        migrations.AddField(
            model_name='student',
            name='studentFirstName',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='studentLastName',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
