# Generated by Django 4.2.5 on 2023-12-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentPortal', '0002_remove_student_studentname_student_studentfirstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='classNumber',
            field=models.CharField(default=None, max_length=8),
        ),
    ]
