# Generated by Django 4.2.5 on 2023-12-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentPortal', '0003_class_classnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='classes', to='studentPortal.class'),
        ),
    ]
