# Generated by Django 4.2.5 on 2023-12-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentPortal', '0004_student_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='studentWaitlist',
            field=models.ManyToManyField(blank=True, related_name='studentWaitlist', to='studentPortal.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='classWaitlist',
            field=models.ManyToManyField(blank=True, related_name='classWaitlist', to='studentPortal.class'),
        ),
    ]
