# Generated by Django 4.2.5 on 2023-12-12 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentPortal', '0005_class_studentwaitlist_student_classwaitlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructorFirstName', models.CharField(default=None, max_length=200)),
                ('instructorLastName', models.CharField(default=None, max_length=200)),
                ('instructorEmail', models.CharField(max_length=200)),
                ('classes', models.ManyToManyField(blank=True, related_name='instructorClasses', to='studentPortal.class')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
